# Generated by Django 4.2.13 on 2026-06-15 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_session', models.CharField(choices=[('CC1', 'Contrôle Continu 1'), ('CC2', 'Contrôle Continu 2'), ('SN', 'Session Normale'), ('SR', 'Session de Rattrapage')], max_length=5)),
                ('date_evaluation', models.DateField()),
                ('statut', models.CharField(choices=[('preparation', 'En préparation'), ('anonymat_actif', 'Anonymat actif'), ('notes_saisies', 'Notes saisies'), ('validee', 'Validée'), ('publiee', 'Publiée')], default='preparation', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.anneescolaire')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cours.matiere')),
            ],
            options={
                'verbose_name': "Session d'évaluation",
                'verbose_name_plural': "Sessions d'évaluation",
            },
        ),
        migrations.CreateModel(
            name='NoteAnonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_anonyme', models.CharField(max_length=10)),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observation', models.CharField(blank=True, max_length=200)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_anonymes', to='notes.session')),
            ],
            options={
                'verbose_name': 'Note anonyme',
                'verbose_name_plural': 'Notes anonymes',
                'unique_together': {('session', 'code_anonyme')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('observation', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='etudiants.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cours.matiere')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.session')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'unique_together': {('session', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='CodeAnonyme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etudiants.etudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_anonymes', to='notes.session')),
            ],
            options={
                'verbose_name': 'Code anonyme',
                'verbose_name_plural': 'Codes anonymes',
                'unique_together': {('session', 'code')},
            },
        ),
    ]
