# Generated by Django 4.2.13 on 2026-06-15 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('intitule', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=3)),
                ('heures_cm', models.IntegerField(default=30)),
                ('heures_td', models.IntegerField(default=15)),
                ('heures_tp', models.IntegerField(default=0)),
                ('annee_scolaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.anneescolaire')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='etudiants.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='etudiants.niveau')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=5)),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='cours.matiere')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
            },
        ),
    ]
