# Generated by Django 4.2.13 on 2026-06-17 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('etudiants', '0001_initial'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField(default=50)),
                ('type_salle', models.CharField(choices=[('amphi', 'Amphithéâtre'), ('salle', 'Salle de cours'), ('labo', 'Laboratoire')], default='salle', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salle',
            },
        ),
        migrations.AddField(
            model_name='seance',
            name='annee_scolaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etudiants.anneescolaire'),
        ),
        migrations.CreateModel(
            name='DisponibiliteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilité enseignant',
                'verbose_name_plural': 'Disponibilités enseignants',
            },
        ),
        migrations.AlterField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.salle'),
        ),
    ]
