# Generated by Django 4.2.13 on 2026-06-15 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalleVirtuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('matiere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salle_virtuelle', to='cours.matiere')),
            ],
            options={
                'verbose_name': 'Salle Virtuelle',
                'verbose_name_plural': 'Salles Virtuelles',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_document', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('EPREUVE', 'Épreuve'), ('CORRIGE', 'Corrigé'), ('AUTRE', 'Autre')], max_length=10)),
                ('fichier', models.FileField(upload_to='salle_virtuelle/documents/')),
                ('description', models.TextField(blank=True)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('annee_reference', models.CharField(blank=True, help_text='Ex: 2023-2024 pour les anciennes épreuves', max_length=10)),
                ('visible', models.BooleanField(default=True)),
                ('telechargements', models.IntegerField(default=0)),
                ('publie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='salle_virtuelle.sallevirtuelle')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('importante', models.BooleanField(default=False)),
                ('publie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='salle_virtuelle.sallevirtuelle')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
            },
        ),
    ]
